sudo: required
services:
  - docker

command: --default-authentication-plugin=mysql_native_password

matrix:
  include:
    - env:
        - DB=mysql:5.5
    - env:
        - DB=mysql:5.6
    - env:
        - DB=mysql:5.7
    - env:
        - DB=mysql:8.0

before_script:
  - ./.travis.install-mysql.sh
  - ./scripts/install_my_prove.sh

script:
  - bash ./install.sh -h 127.0.0.1 -u mytap
  - bash sudo my_prove -v -h 127.0.0.1 -u mytap tests/*.my 