sudo: required
services:
  - docker

matrix:
  include:
    - env:
        - DB=mysql:5.5
    - env:
        - DB=mysql:5.6
    - env:
        - DB=mysql:5.7
    - env:
        - DB=mysql:8.0

before_script:
  - ./.travis.install-mysql.sh
  - export COVERALLS_PARALLEL=true

script: bash ./install.sh

after_success:
  - coveralls

